"""cadastro de clientes do profissional

Revision ID: 0002
Revises: 0001
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('phone_digits', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_from_booking', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_pro_name', 'professional_clients', ['professional_id', 'name'], unique=False)
    op.create_index('ix_client_pro_phone', 'professional_clients', ['professional_id', 'phone_digits'], unique=False)
    op.create_index(op.f('ix_professional_clients_professional_id'), 'professional_clients', ['professional_id'], unique=False)
    op.add_column('bookings', sa.Column('professional_client_id', sa.Integer(), nullable=True))
    # server_default preenche o historico ja existente; sem ele o NOT NULL
    # falharia em qualquer instalacao com agendamentos.
    op.add_column(
        'bookings',
        sa.Column(
            'created_by_professional',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
        ),
    )
    op.create_index(op.f('ix_bookings_professional_client_id'), 'bookings', ['professional_client_id'], unique=False)
    op.create_foreign_key(
        'fk_bookings_professional_client',
        'bookings',
        'professional_clients',
        ['professional_client_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bookings_professional_client', 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_professional_client_id'), table_name='bookings')
    op.drop_column('bookings', 'created_by_professional')
    op.drop_column('bookings', 'professional_client_id')
    op.drop_index(op.f('ix_professional_clients_professional_id'), table_name='professional_clients')
    op.drop_index('ix_client_pro_phone', table_name='professional_clients')
    op.drop_index('ix_client_pro_name', table_name='professional_clients')
    op.drop_table('professional_clients')
    # ### end Alembic commands ###
