"""gatilhos de mensagens automaticas

Revision ID: 0005
Revises: 0004
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.Enum('booking_requested', 'booking_confirmed', 'booking_completed', 'booking_no_show', 'booking_cancelled', 'reminder_before', 'reminder_after', name='notification_trigger'), nullable=False),
    sa.Column('channels', sa.Enum('none', 'email', 'whatsapp', 'both', name='notification_channels'), nullable=False),
    sa.Column('to_client', sa.Boolean(), nullable=False),
    sa.Column('to_professional', sa.Boolean(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('offset_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professional_id', 'trigger', name='uq_rule_pro_trigger')
    )
    op.create_index(op.f('ix_notification_rules_professional_id'), 'notification_rules', ['professional_id'], unique=False)
    op.add_column('messages', sa.Column('trigger', sa.Enum('booking_requested', 'booking_confirmed', 'booking_completed', 'booking_no_show', 'booking_cancelled', 'reminder_before', 'reminder_after', name='notification_trigger'), nullable=True))
    op.create_index(op.f('ix_messages_trigger'), 'messages', ['trigger'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_trigger'), table_name='messages')
    op.drop_column('messages', 'trigger')
    op.drop_index(op.f('ix_notification_rules_professional_id'), table_name='notification_rules')
    op.drop_table('notification_rules')
    # ### end Alembic commands ###
